# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Tue Oct 26 09:18:40 EDT 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-7997-Test
spec:
- template: Test Template
  scheduledStartDate: 2021-10-21T23:30:00-04:00
  dueDate: 2021-10-22T00:30:00-04:00
  phases:
  - phase: Test Phase
    tasks:
    - name: Simple Manual Task
      type: xlrelease.Task
    color: '#3D6C9E'
  riskProfile: Default risk profile
- name: Time Based Trigger
  type: time.Schedule
  releaseTitle: 7997-Release
  template: Test Template
  periodicity: 0 0 9-17 * * MON-FRI
  enabled: false
- directory: SubFolder7997-1
  children:
  - folderVariables:
    - type: xlrelease.StringVariable
      key: folder.Test
      value: Test
  - pattern: "7997"
    stages:
    - stage: New Stage
  - template: Test Template
    scheduledStartDate: 2021-10-21T23:30:00-04:00
    dueDate: 2021-10-22T00:30:00-04:00
    phases:
    - phase: Test Phase
      tasks:
      - name: Simple Manual Task
        type: xlrelease.Task
      color: '#3D6C9E'
    riskProfile: Default risk profile
  - name: Time Based Trigger
    type: time.Schedule
    releaseTitle: 7997-Release
    template: Test Template
    periodicity: 0 0 9-17 * * MON-FRI
    triggerTime: 2021-10-26T09:00:15.318000
  - directory: SubFolder7997
    children:
    - template: Sub-Folder-Test
      scheduledStartDate: 2021-10-21T23:30:00-04:00
      dueDate: 2021-10-22T00:30:00-04:00
      phases:
      - phase: Sub Folder Test
        tasks:
        - name: Create Release Task
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: SubFolder7997
          riskProfile: Default risk profile
          template: ./SubFolder7997-1/Test Template
          folder: ./SubFolder7997-1
        color: '#3D6C9E'
      riskProfile: Default risk profile
    - name: Git Based  trigger
      type: git.Poll
      releaseTitle: SubFOlderTrigger7997
      template: Sub-Folder-Test
      releaseFolder: ./SubFolder7997-1
      gitRepository: Git-Test
      branch: main
      commitId: 0dd5e368ae224baabcacd7dde7c993c32ebd99ef
