# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Mon Dec 20 18:17:51 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8601
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.Another.pass1
    value: !value "xlrelease_PasswordStringVariable_folder_Another_pass1_value"
  - type: xlrelease.PasswordStringVariable
    key: folder.pass2
    value: !value "xlrelease_PasswordStringVariable_folder_pass2_value"
  - type: xlrelease.StringVariable
    key: folder.Pass3
    value: pass3Text
  - type: xlrelease.PasswordStringVariable
    key: folder.pass4
    value: !value "xlrelease_PasswordStringVariable_folder_pass4_value"
- template: Template One
  scheduledStartDate: 2021-12-20T09:00:00+05:30
  dueDate: 2021-12-20T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT1
      type: xlrelease.Task
    - name: MT2
      type: xlrelease.Task
    - name: MT3
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_One_scriptUserPassword"
  riskProfile: Default risk profile
