# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Jan 24 16:46:55 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8239/Sub-8239
spec:
- name: Git-Rest
  type: git.Repository
  variableMapping:
    password: "${global.GLobalPass1}"
  url: https://github.com/SivaprasathDigitalAI/Test_versioning
  username: SivaprasathDigitalAI
- pattern: Patter2
  stages:
  - stage: New Stage
- pattern: Pattern
  stages:
  - stage: Stage One
  - stage: Stage two
- pattern: p
  stages:
  - stage: New Stage
- template: First Template
  scheduledStartDate: 2022-01-24T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
    - name: Custom
      type: databasePlugin.Oracle
      artifactory_url: https://artifactory.server.rbsgrp.net/artifactory
      artifactory_repo: test
      artifact_path: test
      artifact_name: test
      artifact_version: "123"
      property_env: local
      db_user: SivaprasathDigitalAI
      db_host: test
      db_port: "1452"
      database_name: Test
      variableMapping:
        pythonScript.db_password: "${global.GLobalPass1}"
    - name: g
      type: xlrelease.GateTask
  riskProfile: Default risk profile
- name: dummy Dashboasrd
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.TemplateFilter
      template: ENG-8239/Template One
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
  - name: Active releases by risk
    type: live.ReleasesByRiskTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 4
  - name: Tile with custom config
    type: test.TestTileCustomConfig
    row: 0
    col: 5
    supportedScopes:
    - release
    - folder
    - global
- name: Parent Trigger
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: 8239_template
  - type: xlrelease.StringValue
    targetProperty: template
    value: First Template
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: ENG-8239/Sub-8239
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: Global Webhook
  eventType: events.HttpRequestEvent
- name: Trigger One
  type: git.Poll
  enabled: false
  releaseTitle: SUb8239
  template: First Template
  releaseFolder: ./
  gitRepository: Github-8239
  branch: Main
- directory: SubSub8239
  children:
  - pattern: SubSub8239
    stages:
    - stage: New Stage
    - stage: New Stage (1)
    - stage: New Stage (2)
  - template: Template Two
    scheduledStartDate: 2022-01-24T09:00:00+05:30
    phases:
    - phase: New Phase
      tasks:
      - name: MTG1
        type: xlrelease.Task
    riskProfile: Default risk profile
  - name: DashBoard
    type: xlrelease.BlankDashboard
    owner: admin
  - name: Trigger Test
    type: events.EventBasedTrigger
    enabled: false
    mappedProperties:
    - type: xlrelease.StringValue
      targetProperty: releaseTitle
      value: 8239_SUB_SUB
    - type: xlrelease.StringValue
      targetProperty: template
      value: Template Two
    - type: xlrelease.StringValue
      targetProperty: releaseFolder
      value: ENG-8239
    triggerActionType: xlrelease.CreateReleaseFromTemplateAction
    eventSource: ENG-8239
    eventType: events.HttpRequestEvent
  - name: Trigger Two
    type: jira.IssueTrigger
    enabled: false
    releaseTitle: Eng8239
    template: Template Two
    releaseFolder: ENG-8239
    jql: assignee ='test'
    server: Jira-test
  - notifications:
    - notification: TASK_OVERDUE
      priority: High
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release is overdue.

        After the task is completed, please mark it as Completed in Release.
      roles:
      - Watcher
      - Release Admin
      - Task Owner
    - notification: TASK_FLAGGED
      priority: High
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

        **${release.flagComment}**
      roles:
      - Watcher
      - Release Admin
      - Task Team
    - notification: AUDIT_REPORT_JOB_ABORTED
      priority: Normal
      subject: "[Release] Audit report was aborted"
      body: |-
        **Your audit report was aborted!**

         Please try to generate it again or contact your Release administrator for assistance.
    - notification: MANUAL_TASK_STARTED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

        After the task is completed, please mark it as Completed in Release.
      roles:
      - Watcher
      - Task Owner
    - notification: TASK_FAILED
      priority: High
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release has failed.

        Other tasks could still be in progress, but the release will stop after they complete.

        You can retry the task, reassign it to somebody else or abort the release.
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: USER_MENTIONED
      priority: Normal
      subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
        \ ${task.title}"
      body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
        \ in the **${release.title}** release:"
    - notification: COMMENT_ADDED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

        ${comment.text}
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: AUDIT_REPORT_JOB_FAILED
      priority: Normal
      subject: "[Release] Audit report has failed"
      body: |-
        **Your audit report has failed!**

         Please try to generate it again or contact your Release administrator for assistance.
    - notification: RELEASE_FAILED
      priority: High
      subject: "[Release] ${release.title}"
      body: |-
        The **${release.title}** release has failed due to a task failure.

        The release is now stopped.

        You can retry the failed task, reassign it to somebody else or abort the release.
      roles:
      - Release Admin
    - notification: TASK_DUE_SOON
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

        After the task is completed, please mark it as Completed in Release.
      roles:
      - Watcher
      - Release Admin
      - Task Owner
    - notification: ACTIVE_TASK_UNASSIGNED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

        Please assign the task to a user or a team.
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: RELEASE_FAILING
      priority: High
      subject: "[Release] ${release.title}"
      body: |-
        The **${release.title}** release is failing due to a task failure.

        Other tasks may still be in progress, but the release will stop after they complete.

        You can retry the failed task, reassign it to somebody else or abort the release.
      roles:
      - Release Admin
    - notification: RELEASE_FLAGGED
      priority: High
      subject: "[Release] ${release.title}"
      body: |-
        The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

        **${release.flagComment}**
      roles:
      - Release Admin
    - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

        Please assign the task to a user or a team.
      roles:
      - Watcher
      - Release Admin
    - notification: RELEASE_COMPLETED
      priority: Normal
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has been completed."
      roles:
      - Release Admin
    - notification: TASK_WAITING_FOR_INPUT
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: |-
        The **${task.title}** task in the **${release.title}** release needs your input.

        Please enter the required information so the release can continue.
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: AUDIT_REPORT_JOB_COMPLETED
      priority: Normal
      subject: "[Release] Report '${report.reportName}' is ready"
      body: |-
        **Your audit report is complete!**

         '${report.reportName}' is ready for download.
    - notification: RELEASE_STARTED
      priority: Normal
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has been started."
      bulkSubject: "[Release] Multiple releases started"
      bulkBody: |-
        The following releases have been started:

        ${#releases}
        * [${title}](${url})
        ${/releases}
      roles:
      - Release Admin
    - notification: RELEASE_ABORTED
      priority: Normal
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has been aborted."
      bulkSubject: "[Release] Multiple releases aborted"
      bulkBody: |-
        The following releases have been aborted:

        ${#releases}
        * [${title}](${url})
        ${/releases}
      roles:
      - Release Admin
    - notification: ACTIVE_TASK_ASSIGNED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The active task **${task.title}** in the **${release.title}** release\
        \ is now assigned to ${task.ownerFullName}."
      roles:
      - Watcher
      - Task Team
      - Task Owner
- notifications:
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release is overdue.\r\
      \n\r\nAfter the task is completed, please mark it as Completed in Release."
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The status of the **${task.title}** task in the **${release.title}** release\
      \ was changed to **${task.flagStatus}** with the following comment:\r\n\r\n\
      **${release.flagComment}**"
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: AUDIT_REPORT_JOB_ABORTED
    priority: Normal
    subject: "[Release] Audit report was aborted"
    body: "**Your audit report was aborted!**\r\n\r\n Please try to generate it again\
      \ or contact your Release administrator for assistance."
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release has started\
      \ and is assigned to you or your team.\r\n\r\nAfter the task is completed, please\
      \ mark it as Completed in Release."
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release has failed.\r\
      \n\r\nOther tasks could still be in progress, but the release will stop after\
      \ they complete.\r\n\r\nYou can retry the task, reassign it to somebody else\
      \ or abort the release."
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: USER_MENTIONED
    priority: Normal
    subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
      \ ${task.title}"
    body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
      \ in the **${release.title}** release:"
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "**${comment.authorFullName}** commented on the **${task.title}** task in\
      \ the **${release.title}** release:\r\n\r\n${comment.text}"
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_FAILED
    priority: Normal
    subject: "[Release] Audit report has failed"
    body: "**Your audit report has failed!**\r\n\r\n Please try to generate it again\
      \ or contact your Release administrator for assistance."
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has failed due to a task failure.\r\n\r\
      \nThe release is now stopped.\r\n\r\nYou can retry the failed task, reassign\
      \ it to somebody else or abort the release."
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release is due in\
      \ **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.\r\n\r\n\
      After the task is completed, please mark it as Completed in Release."
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release is active\
      \ but not assigned to anyone anymore.\r\n\r\nPlease assign the task to a user\
      \ or a team."
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release is failing due to a task failure.\r\n\r\
      \nOther tasks may still be in progress, but the release will stop after they\
      \ complete.\r\n\r\nYou can retry the failed task, reassign it to somebody else\
      \ or abort the release."
    roles:
    - Release Admin
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: "The status of the **${release.title}** release was changed to **${release.flagStatus}**\
      \ with the following comment:\r\n\r\n**${release.flagComment}**"
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release has started,\
      \ but it is not assigned.\r\n\r\nPlease assign the task to a user or a team."
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release needs your\
      \ input.\r\n\r\nPlease enter the required information so the release can continue."
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_COMPLETED
    priority: Normal
    subject: "[Release] Report '${report.reportName}' is ready"
    body: "**Your audit report is complete!**\r\n\r\n '${report.reportName}' is ready\
      \ for download."
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    bulkSubject: "[Release] Multiple releases started"
    bulkBody: "The following releases have been started:\r\n\r\n${#releases}\r\n*\
      \ [${title}](${url})\r\n${/releases}"
    roles:
    - Release Admin
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    bulkSubject: "[Release] Multiple releases aborted"
    bulkBody: "The following releases have been aborted:\r\n\r\n${#releases}\r\n*\
      \ [${title}](${url})\r\n${/releases}"
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}."
    roles:
    - Watcher
    - Task Team
    - Task Owner
