# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      22.2.0-314.113
# Date created:         Mon Mar 21 07:10:50 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder-One
spec:
- template: T1
  scheduledStartDate: 2022-03-21T04:30:00+01:00
  phases:
  - phase: New Phase
  variables:
  - type: xlrelease.PasswordStringVariable
    key: password
    requiresValue: false
    showOnReleaseStart: false
  riskProfile: Default risk profile
