# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      22.2.0-314.113
# Date created:         Mon Mar 21 12:57:18 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder-One
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.WebHooksPassword
    value: !value "xlrelease_PasswordStringVariable_folder_WebHooksPassword_value"
  - type: xlrelease.PasswordStringVariable
    key: folder.folderPass2
    value: !value "xlrelease_PasswordStringVariable_folder_folderPass2_value"
- name: Get
  type: events.GetWebhookEndpoint
  variableMapping:
    authentication.webhookToken: "${folder.WebHooksPassword}"
  path: test
  authentication:
    type: events.TokenAuthentication
- template: T1
  scheduledStartDate: 2022-03-21T04:30:00+01:00
  dueDate: 2022-03-21T05:30:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: MT1
      type: xlrelease.Task
  variables:
  - type: xlrelease.PasswordStringVariable
    key: password
    requiresValue: false
    showOnReleaseStart: false
  riskProfile: Default risk profile
- name: Trigger One
  type: events.EventBasedTrigger
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: FOlder One-R
  - type: xlrelease.StringValue
    targetProperty: template
    value: T1
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: ./
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: GLOBAL_GET_WEBHOOK
  eventType: events.HttpRequestEvent
