# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      22.2.0-314.113
# Date created:         Mon Mar 21 07:13:43 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder-One
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.WebHooksPassword
    value: !value "xlrelease_PasswordStringVariable_folder_WebHooksPassword_value"
- name: Get
  type: events.GetWebhookEndpoint
  variableMapping:
    authentication.webhookToken: "${folder.WebHooksPassword}"
  path: test
  authentication:
    type: events.TokenAuthentication
- template: T1
  scheduledStartDate: 2022-03-21T04:30:00+01:00
  phases:
  - phase: New Phase
  variables:
  - type: xlrelease.PasswordStringVariable
    key: password
    requiresValue: false
    showOnReleaseStart: false
  riskProfile: Default risk profile
