# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Fri Oct 01 07:00:32 EDT 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-7561
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.dummyFolderVariable
    label: Dummy
    description: Created for testing  ENG7737
    value: Some Dummy Value
- pattern: ENG-7561-Pattern
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
  - stage: New Stage (1)
  - stage: New Stage (2)
- pattern: ENG-7561-Pattern Activity Test
  stages:
  - stage: Simple 7561
    transition:
      name: New Transition
      type: delivery.Transition
  - stage: New Stage (1)
- pattern: Test
  stages:
  - stage: New Stage
- pattern: Test-1
  stages:
  - stage: New Stage
- pattern: Test-Again
  stages:
  - stage: New Stage
- template: ENG-7561-Template
  scheduledStartDate: 2021-09-28T23:30:00-04:00
  dueDate: 2021-09-29T00:30:00-04:00
  phases:
  - phase: ENG-7561-Phase
    tasks:
    - name: ENG-7561-MT
      type: xlrelease.Task
    - name: Test-Delivery
      type: delivery.CreateDelivery
      ^title: testing
      pattern: ./ENG-7561-Pattern
      folder: ./
    - name: jscript
      type: xlrelease.ScriptTask
    color: '#0079BC'
  - phase: ENG-7562-Phase2
    tasks:
    - name: Deli
      type: delivery.CreateDelivery
    - name: Remote
      type: remoteScript.Windows
    - name: Json
      type: webhook.JsonWebhook
    - name: Test
      type: databasePlugin.Oracle
    color: '#0079BC'
  riskProfile: Default risk profile
- name: Blank DashBoard
  type: xlrelease.BlankDashboard
  description: Simple Dash Board For Testing
  owner: admin
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 0
    col: 4
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 7
  - name: Active releases by risk
    type: live.ReleasesByRiskTile
    row: 2
    col: 0
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 2
    col: 2
  - name: Latest commits
    type: test.LatestCommitsTile
    row: 1
    col: 7
    supportedScopes:
    - release
    - folder
    - global
  - name: Time spent by task category
    type: xlrelease.TaskTimeSpentTile
  columns: 8
- name: ggg
  type: xlrelease.BlankDashboard
  description: www
  owner: admin
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by risk
    type: live.ReleasesByRiskTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: JIRA issues
    type: jira.JiraQueryTile
    row: 0
    col: 4
  - name: Latest commits
    type: test.LatestCommitsTile
    row: 0
    col: 5
    supportedScopes:
    - release
    - folder
    - global
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 2
    col: 0
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 2
    col: 3
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 4
    col: 0
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 4
    col: 3
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 6
    col: 0
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 6
    col: 3
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 8
    col: 0
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    row: 1
    col: 4
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 8
    col: 3
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
- notifications:
  - notification: TASK_OVERDUE
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is overdue. Tested TASK_OVERDUE

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: AUDIT_REPORT_JOB_ABORTED
    priority: Normal
    subject: "[Release] Audit report was aborted"
    body: |-
      **Your audit report was aborted!**

       Please try to generate it again or contact your Release administrator for assistance.
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has failed. Test_Failed Tested

      Other tasks could still be in progress, but the release will stop after they complete.

      You can retry the task, reassign it to somebody else or abort the release.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: USER_MENTIONED
    priority: Normal
    subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
      \ ${task.title}"
    body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
      \ in the **${release.title}** release:"
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

      ${comment.text}
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_FAILED
    priority: Normal
    subject: "[Release] Audit report has failed"
    body: |-
      **Your audit report has failed!**

       Please try to generate it again or contact your Release administrator for assistance.
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release has failed due to a task failure.

      The release is now stopped.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release is failing due to a task failure.

      Other tasks may still be in progress, but the release will stop after they complete. Tested RELEASE_FAILING

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Low
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release needs your input.

      Please enter the required information so the release can continue.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_COMPLETED
    priority: Normal
    subject: "[Release] Report '${report.reportName}' is ready"
    body: |-
      **Your audit report is complete!**

       '${report.reportName}' is ready for download.
  - notification: RELEASE_STARTED
    priority: High
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    bulkSubject: "[Release] Multiple releases started"
    bulkBody: |-
      The following releases have been started:

      ${#releases}
      * [${title}](${url})
      ${/releases}
    roles:
    - Release Admin
  - notification: RELEASE_ABORTED
    priority: Low
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted. Tested RELEASE_ABORTED"
    bulkSubject: "[Release] Multiple releases aborted"
    bulkBody: |-
      The following releases have been aborted:

      ${#releases}
      * [${title}](${url})
      ${/releases}
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}."
    roles:
    - Watcher
    - Task Team
    - Task Owner
