# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Dec 21 13:58:46 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-7560
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.First.pass
- template: Test Template
  scheduledStartDate: 2021-12-21T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
