# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Tue Oct 26 10:13:18 EDT 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-4545
spec:
- pattern: ENG-7560-Pattern
  stages:
  - stage: New Stage
    transition:
      name: New Transition1
      type: delivery.Transition
  - stage: New Stage (1)
- pattern: Simple-Delivery-Test
  stages:
  - stage: New Stage
- pattern: Test-11
  stages:
  - stage: New Stage
- pattern: Test-ENG4545
  stages:
  - stage: New Stage
- pattern: test12
  stages:
  - stage: New Stage
- name: Release statistics
  type: xlrelease.ReleaseStatisticsDashboard
  owner: admin
  tiles:
  - name: Longest task type
    type: xlrelease.LongestTaskTypeTile
    row: 0
    col: 1
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Number of releases
    type: xlrelease.ReleasesByMonthTile
    row: 2
    col: 3
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Release efficiency
    type: xlrelease.ReleaseEfficiencyTile
    row: 2
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 1
    col: 1
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Time spent by task category
    type: xlrelease.TaskTimeSpentTile
    row: 0
    col: 4
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Avg. release duration
    type: xlrelease.AvgReleaseDurationTile
    row: 1
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Task efficiency
    type: xlrelease.TaskEfficiencyTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Top 10 longest releases
    type: xlrelease.LongestReleasesTile
    row: 4
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 4
    col: 3
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Top 10 longest phases
    type: xlrelease.LongestPhasesTile
    row: 6
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 6
    col: 3
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  filters:
  - type: xlrelease.FolderFilter
    folder: ./
  - type: xlrelease.DateFilter
