# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Dec 21 15:09:49 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-7560
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.First.pass
- pattern: test one
  stages:
  - stage: New Stage
- template: Test Template
  scheduledStartDate: 2021-12-21T09:00:00+05:30
  dueDate: 2021-12-21T10:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- name: Test Trigger
  type: time.Schedule
  releaseTitle: "7560"
  template: Test Template
  releaseFolder: ./
  periodicity: 0 0 9-17 * * MON
