# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Thu Sep 09 03:29:53 EDT 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-4545
spec:
- pattern: Test-ENG4545
  stages:
  - stage: New Stage
- template: triggered Template1
  scheduledStartDate: 2021-09-01T23:30:00-04:00
  dueDate: 2021-09-02T00:30:00-04:00
  phases:
  - phase: New Phase
    tasks:
    - name: Task
      type: xlrelease.ParallelGroup
      tasks:
      - name: test
        type: xlrelease.Task
    - name: Release
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: test
      riskProfile: Default risk profile
      template: Triggers-test/triggered Template
      folder: ./Sub-Triggers-test1
    - name: Delivery
      type: delivery.CreateDelivery
      ^title: Test
      pattern: Test/Simple-Delivery
      folder: ./
      variableMapping:
        pythonScript.deliveryId: "${SumpleDelivery}"
    - name: Deli-2
      type: delivery.FindOrCreateDelivery
      pattern: ./Test-ENG4545
      folder: ./
  variables:
  - type: xlrelease.StringVariable
    key: SumpleDelivery
    requiresValue: false
    showOnReleaseStart: false
  riskProfile: Default risk profile
- name: Release statistics
  type: xlrelease.ReleaseStatisticsDashboard
  owner: admin
  tiles:
  - name: Longest task type
    type: xlrelease.LongestTaskTypeTile
    row: 0
    col: 1
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Number of releases
    type: xlrelease.ReleasesByMonthTile
    row: 2
    col: 3
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Release efficiency
    type: xlrelease.ReleaseEfficiencyTile
    row: 2
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 1
    col: 1
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Time spent by task category
    type: xlrelease.TaskTimeSpentTile
    row: 0
    col: 4
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Avg. release duration
    type: xlrelease.AvgReleaseDurationTile
    row: 1
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Task efficiency
    type: xlrelease.TaskEfficiencyTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Top 10 longest releases
    type: xlrelease.LongestReleasesTile
    row: 4
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 4
    col: 3
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Top 10 longest phases
    type: xlrelease.LongestPhasesTile
    row: 6
    col: 0
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 6
    col: 3
    filters:
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  filters:
  - type: xlrelease.FolderFilter
    folder: ./
  - type: xlrelease.DateFilter
- name: Event-Trigger-sub
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: sub-folder-test
  - type: xlrelease.ListStringValue
    targetProperty: tags
    value:
    - sub
  - type: xlrelease.StringValue
    targetProperty: template
    value: triggered Template1
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: ./Sub-Triggers-test1
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: Trigger-Test
  eventType: events.HttpRequestEvent
- name: Event-test
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Simple-Test
  - type: xlrelease.ListStringValue
    targetProperty: tags
    value:
    - test
  - type: xlrelease.StringValue
    targetProperty: template
    value: triggered Template1
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: Test-Links
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: Trigger-Test
  eventType: events.HttpRequestEvent
- name: git-trigger
  type: git.Poll
  enabled: false
  releaseTitle: trigger
  template: triggered Template1
  tags:
  - eee
  gitRepository: Git-Test
  branch: main
  commitId: 68993dab6e809404352110b752afef6120f931d5
- name: jira
  type: jira.IssueTrigger
  enabled: false
  releaseTitle: jira
  template: triggered Template1
  jql: select issue_id
  server: Jira
  username: test1
  password: !value "jira_IssueTrigger_jira_password"
- directory: Sub-Triggers-test1
  children:
  - template: Simple-test
    scheduledStartDate: 2021-09-01T23:30:00-04:00
    dueDate: 2021-09-02T00:30:00-04:00
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
  - notifications:
    - notification: TASK_OVERDUE
      priority: High
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release is overdue.\r\
        \n\r\nAfter the task is completed, please mark it as Completed in Release."
      roles:
      - Watcher
      - Release Admin
      - Task Owner
    - notification: TASK_FLAGGED
      priority: High
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The status of the **${task.title}** task in the **${release.title}**\
        \ release was changed to **${task.flagStatus}** with the following comment:\r\
        \n\r\n**${release.flagComment}**"
      roles:
      - Watcher
      - Release Admin
      - Task Team
    - notification: AUDIT_REPORT_JOB_ABORTED
      priority: Normal
      subject: "[Release] Audit report was aborted"
      body: "**Your audit report was aborted!**\r\n\r\n Please try to generate it\
        \ again or contact your Release administrator for assistance."
    - notification: MANUAL_TASK_STARTED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release has started\
        \ and is assigned to you or your team.\r\n\r\nAfter the task is completed,\
        \ please mark it as Completed in Release."
      roles:
      - Watcher
      - Task Owner
    - notification: TASK_FAILED
      priority: High
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release has failed.\r\
        \n\r\nOther tasks could still be in progress, but the release will stop after\
        \ they complete.\r\n\r\nYou can retry the task, reassign it to somebody else\
        \ or abort the release."
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: USER_MENTIONED
      priority: Normal
      subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
        \ ${task.title}"
      body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
        \ in the **${release.title}** release:"
    - notification: COMMENT_ADDED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "**${comment.authorFullName}** commented on the **${task.title}** task\
        \ in the **${release.title}** release:\r\n\r\n${comment.text}"
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: AUDIT_REPORT_JOB_FAILED
      priority: Normal
      subject: "[Release] Audit report has failed"
      body: "**Your audit report has failed!**\r\n\r\n Please try to generate it again\
        \ or contact your Release administrator for assistance."
    - notification: RELEASE_FAILED
      priority: High
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has failed due to a task failure.\r\n\
        \r\nThe release is now stopped.\r\n\r\nYou can retry the failed task, reassign\
        \ it to somebody else or abort the release."
      roles:
      - Release Admin
    - notification: TASK_DUE_SOON
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release is due\
        \ in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.\r\n\
        \r\nAfter the task is completed, please mark it as Completed in Release."
      roles:
      - Watcher
      - Release Admin
      - Task Owner
    - notification: ACTIVE_TASK_UNASSIGNED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release is active\
        \ but not assigned to anyone anymore.\r\n\r\nPlease assign the task to a user\
        \ or a team."
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: RELEASE_FAILING
      priority: High
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release is failing due to a task failure.\r\n\
        \r\nOther tasks may still be in progress, but the release will stop after\
        \ they complete.\r\n\r\nYou can retry the failed task, reassign it to somebody\
        \ else or abort the release."
      roles:
      - Release Admin
    - notification: RELEASE_FLAGGED
      priority: High
      subject: "[Release] ${release.title}"
      body: "The status of the **${release.title}** release was changed to **${release.flagStatus}**\
        \ with the following comment:\r\n\r\n**${release.flagComment}**"
      roles:
      - Release Admin
    - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release has started,\
        \ but it is not assigned.\r\n\r\nPlease assign the task to a user or a team."
      roles:
      - Watcher
      - Release Admin
    - notification: RELEASE_COMPLETED
      priority: Normal
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has been completed."
      roles:
      - Release Admin
    - notification: TASK_WAITING_FOR_INPUT
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The **${task.title}** task in the **${release.title}** release needs\
        \ your input.\r\n\r\nPlease enter the required information so the release\
        \ can continue."
      roles:
      - Watcher
      - Task Team
      - Task Owner
    - notification: AUDIT_REPORT_JOB_COMPLETED
      priority: Normal
      subject: "[Release] Report '${report.reportName}' is ready"
      body: "**Your audit report is complete!**\r\n\r\n '${report.reportName}' is\
        \ ready for download."
    - notification: RELEASE_STARTED
      priority: Normal
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has been started."
      bulkSubject: "[Release] Multiple releases started"
      bulkBody: "The following releases have been started:\r\n\r\n${#releases}\r\n\
        * [${title}](${url})\r\n${/releases}"
      roles:
      - Release Admin
    - notification: RELEASE_ABORTED
      priority: Normal
      subject: "[Release] ${release.title}"
      body: "The **${release.title}** release has been aborted."
      bulkSubject: "[Release] Multiple releases aborted"
      bulkBody: "The following releases have been aborted:\r\n\r\n${#releases}\r\n\
        * [${title}](${url})\r\n${/releases}"
      roles:
      - Release Admin
    - notification: ACTIVE_TASK_ASSIGNED
      priority: Normal
      subject: "[Release] ${release.title}: ${task.title}"
      body: "The active task **${task.title}** in the **${release.title}** release\
        \ is now assigned to ${task.ownerFullName}."
      roles:
      - Watcher
      - Task Team
      - Task Owner
- notifications:
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release is overdue.\r\
      \n\r\nAfter the task is completed, please mark it as Completed in Release."
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The status of the **${task.title}** task in the **${release.title}** release\
      \ was changed to **${task.flagStatus}** with the following comment:\r\n\r\n\
      **${release.flagComment}**"
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: AUDIT_REPORT_JOB_ABORTED
    priority: Normal
    subject: "[Release] Audit report was aborted"
    body: "**Your audit report was aborted!**\r\n\r\n Please try to generate it again\
      \ or contact your Release administrator for assistance."
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release has started\
      \ and is assigned to you or your team.\r\n\r\nAfter the task is completed, please\
      \ mark it as Completed in Release."
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release has failed.\r\
      \n\r\nOther tasks could still be in progress, but the release will stop after\
      \ they complete.\r\n\r\nYou can retry the task, reassign it to somebody else\
      \ or abort the release."
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: USER_MENTIONED
    priority: Normal
    subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
      \ ${task.title}"
    body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
      \ in the **${release.title}** release:"
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "**${comment.authorFullName}** commented on the **${task.title}** task in\
      \ the **${release.title}** release:\r\n\r\n${comment.text}"
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_FAILED
    priority: Normal
    subject: "[Release] Audit report has failed"
    body: "**Your audit report has failed!**\r\n\r\n Please try to generate it again\
      \ or contact your Release administrator for assistance."
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has failed due to a task failure.\r\n\r\
      \nThe release is now stopped.\r\n\r\nYou can retry the failed task, reassign\
      \ it to somebody else or abort the release."
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release is due in\
      \ **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.\r\n\r\n\
      After the task is completed, please mark it as Completed in Release."
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release is active\
      \ but not assigned to anyone anymore.\r\n\r\nPlease assign the task to a user\
      \ or a team."
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release is failing due to a task failure.\r\n\r\
      \nOther tasks may still be in progress, but the release will stop after they\
      \ complete.\r\n\r\nYou can retry the failed task, reassign it to somebody else\
      \ or abort the release."
    roles:
    - Release Admin
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: "The status of the **${release.title}** release was changed to **${release.flagStatus}**\
      \ with the following comment:\r\n\r\n**${release.flagComment}**"
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release has started,\
      \ but it is not assigned.\r\n\r\nPlease assign the task to a user or a team."
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The **${task.title}** task in the **${release.title}** release needs your\
      \ input.\r\n\r\nPlease enter the required information so the release can continue."
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_COMPLETED
    priority: Normal
    subject: "[Release] Report '${report.reportName}' is ready"
    body: "**Your audit report is complete!**\r\n\r\n '${report.reportName}' is ready\
      \ for download."
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    bulkSubject: "[Release] Multiple releases started"
    bulkBody: "The following releases have been started:\r\n\r\n${#releases}\r\n*\
      \ [${title}](${url})\r\n${/releases}"
    roles:
    - Release Admin
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    bulkSubject: "[Release] Multiple releases aborted"
    bulkBody: "The following releases have been aborted:\r\n\r\n${#releases}\r\n*\
      \ [${title}](${url})\r\n${/releases}"
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}."
    roles:
    - Watcher
    - Task Team
    - Task Owner
