# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Mon Dec 20 19:36:39 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8601_5
spec:
- template: Template-One
  scheduledStartDate: 2021-12-20T09:00:00+05:30
  dueDate: 2021-12-20T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT1
      type: xlrelease.Task
    - name: MT2
      type: xlrelease.Task
    - name: MT3
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_One_scriptUserPassword"
  riskProfile: Default risk profile
