# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Dec 20 20:24:40 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8601
spec:
- template: PONe
  scheduledStartDate: 2021-12-20T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT1
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_PONe_scriptUserPassword"
  riskProfile: Default risk profile
