# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      23.1.0
# Date created:         Tue Sep 12 12:31:58 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: workflows
spec:
- directory: Digital.ai Deploy
  children:
  - name: TestSiva
    type: git.Repository
    url: https://github.com/SivaprasathDigitalAI/sample-test
    username: SivaprasathDigitalAI
    password: !value "git_Repository_TestSiva_password"
