# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      23.1.0
# Date created:         Tue Sep 12 12:31:58 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: workflows
spec:
- directory: Digital.ai Deploy
  children:
  - template: T1
    scheduledStartDate: 2023-08-28T09:00:00+05:30
    dueDate: 2023-08-28T10:00:00+05:30
    phases:
    - phase: New Phase
      tasks:
      - name: MT
        type: xlrelease.Task
      - name: SQ
        type: xlrelease.SequentialGroup
        tasks:
        - name: DD
          type: delivery.CreateDelivery
          ^title: EEEE
          pattern: ./Digital.ai Deploy/P1
          folder: ./Digital.ai Deploy
          variableMapping:
            pythonScript.deliveryId: "${deliveryId}"
        - name: FCD
          type: delivery.FindOrCreateDelivery
          fallback: true
          ^title: DDDDD
          pattern: ./Digital.ai Deploy/P1
          folder: ./Digital.ai Deploy
          variableMapping:
            pythonScript.deliveryId: "${deliveryId2}"
        - name: MT
          type: delivery.MarkTrackedItems
          precedingStages: true
          stage: New Stage
          delivery: "${deliveryId}"
          pattern: ./Digital.ai Deploy/P1
    variables:
    - type: xlrelease.StringVariable
      key: deliveryId
      requiresValue: false
      showOnReleaseStart: false
    - type: xlrelease.StringVariable
      key: deliveryId2
      requiresValue: false
      showOnReleaseStart: false
    riskProfile: Default risk profile
