# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Dec 22 15:15:44 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8601
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.pass
    value: !value "xlrelease_PasswordStringVariable_folder_pass_value"
- name: Another Repo
  type: git.Repository
  variableMapping:
    password: "${global.git.credentials}"
  url: https://github.com/SivaprasathDigitalAI/TestRepo
  username: SivaprasathDigitalAI_1
- name: Git -8601
  type: git.Repository
  variableMapping:
    password: "${global.git.credentials}"
  url: https://github.com/SivaprasathDigitalAI/sample-test
  username: SivaprasathDigitalAI_1
- name: Jenkin
  type: jenkins.Server
  url: http://localHost:8090
  username: admin
  password: !value "jenkins_Server_Jenkin_password"
- template: First Template
  scheduledStartDate: 2021-12-20T09:00:00+05:30
  dueDate: 2021-12-20T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT!
      type: xlrelease.Task
    - name: MT2
      type: xlrelease.Task
    - name: Test
      type: databasePlugin.Oracle
      db_password: !value "databasePlugin_Oracle_Test_db_password"
  scriptUsername: admin
  riskProfile: Default risk profile
- name: Trigger-One
  type: git.Poll
  releaseTitle: ENG-8601-Rel
  template: First Template
  releaseFolder: ./
  gitRepository: Git -8601
  branch: main
  username: sivaprasath
