# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Dec 23 14:02:51 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8601
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.pass
- name: Another Repo
  type: git.Repository
  variableMapping:
    password: "${global.git.credentials}"
  url: https://github.com/SivaprasathDigitalAI/TestRepo
  username: SivaprasathDigitalAI_1
- name: Jenkin
  type: jenkins.Server
  url: http://localHost:8090
  username: admin
- name: Git-8601
  type: xlrelease.GitHubScmConnectorConfig
  variableMapping:
    credential.token: "${global.git.credentials}"
  repository: SivaprasathDigitalAI/sample-test
  branch: main
  credential:
    type: xlrelease.GitHubOAuth2Token
- template: First Template
  scheduledStartDate: 2021-12-20T09:00:00+05:30
  dueDate: 2021-12-20T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT!
      type: xlrelease.Task
    - name: MT2
      type: xlrelease.Task
    - name: Test
      type: databasePlugin.Oracle
  variables:
  - type: xlrelease.PasswordStringVariable
    key: Template
    value: !value "xlrelease_PasswordStringVariable_Template_value"
  scriptUsername: admin
  riskProfile: Default risk profile
- name: Trigger-One
  type: git.Poll
  releaseTitle: ENG-8601-Rel
  variables:
  - type: xlrelease.PasswordStringVariable
    key: Template
    value: !value "xlrelease_PasswordStringVariable_Template_value_0"
  template: First Template
  releaseFolder: ./
  gitRepository: Git -8601
  branch: main
  username: sivaprasath
