# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue May 23 18:36:22 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test-Teams
spec:
- pattern: T1
  stages:
  - stage: New Stage
  - stage: New Stage (1)
