# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Mar 21 16:54:09 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-9397
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.pass1
    value: !value "xlrelease_PasswordStringVariable_folder_pass1_value"
  - type: xlrelease.PasswordStringVariable
    key: folder.pass2
    value: !value "xlrelease_PasswordStringVariable_folder_pass2_value"
- template: Template 1
  scheduledStartDate: 2022-03-16T09:00:00+05:30
  dueDate: 2022-03-16T10:00:00+05:30
  phases:
  - phase: New Phase
  variables:
  - type: xlrelease.StringVariable
    key: ListBox
    label: List Box
    valueProvider:
      type: test.TestValueProvider
      param2: "100"
  - type: xlrelease.StringVariable
    key: Fixed Value ListBox
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - one
      - two
    value: one
  - type: xlrelease.StringVariable
    key: String var1
    value: T1
  - type: xlrelease.PasswordStringVariable
    key: Pass Var
    label: Pass Var
    value: !value "xlrelease_PasswordStringVariable_Pass_Var_value"
  riskProfile: Default risk profile
- template: Template 2
  scheduledStartDate: 2022-03-16T09:00:00+05:30
  dueDate: 2022-03-16T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: CR1
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: CRT Release
      templateVariables:
      - type: xlrelease.StringVariable
        key: ListBox
        label: List Box
        value: "4"
      - type: xlrelease.StringVariable
        key: Fixed Value ListBox
        inherited: true
        value: one
      - type: xlrelease.StringVariable
        key: String var1
        inherited: true
        value: T1
      - type: xlrelease.PasswordStringVariable
        key: Pass Var
        label: Pass Var
        inherited: true
      riskProfile: Default risk profile
      template: ./Template 1
      folder: ./
  riskProfile: Default risk profile
- name: Trigger One
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: ENG-9397
  - type: xlrelease.StringValue
    targetProperty: template
    value: Template 2
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: ./
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: Global_GET_WEBHOOK
  eventType: events.HttpRequestEvent
