# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Jan 12 10:57:31 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8604
spec:
- pattern: Pattern One
  stages:
  - stage: Stage One
  - stage: Stage Two
- template: Template One
  scheduledStartDate: 2022-01-03T09:00:00+05:30
  dueDate: 2022-01-03T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  scriptUsername: admin
  riskProfile: Default risk profile
- name: Test DashBoard
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 0
  - name: JIRA issues
    type: jira.JiraQueryTile
    row: 0
    col: 1
    username: sivaprasath.subramaniyan@digital.ai
    query: select * from table
  - name: Latest commits
    type: test.LatestCommitsTile
    row: 0
    col: 2
    supportedScopes:
    - release
    - folder
    - global
  - name: Top 10 task assignees
    type: xlrelease.TopTenTaskAssigneeTile
    row: 0
    col: 3
  columns: 8
- name: Test DashBoard (Copy)
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 0
  - name: JIRA issues
    type: jira.JiraQueryTile
    row: 0
    col: 1
    username: sivaprasath.subramaniyan@digital.ai
    query: select * from table
  - name: Latest commits
    type: test.LatestCommitsTile
    row: 0
    col: 2
    supportedScopes:
    - release
    - folder
    - global
  - name: Top 10 task assignees
    type: xlrelease.TopTenTaskAssigneeTile
    row: 0
    col: 3
  columns: 8
