# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Jan 12 10:30:24 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8604
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.Folder1pass
- name: Test
  type: jenkins.Server
  url: http://localhost
  username: test
  password: !value "jenkins_Server_Test_password"
- name: Digital
  type: jira.Server
  url: http://localhost
  username: adminh
  password: !value "jira_Server_Digital_password"
- pattern: Pattern One
  stages:
  - stage: Stage One
  - stage: Stage Two
- template: Template One
  scheduledStartDate: 2022-01-03T09:00:00+05:30
  dueDate: 2022-01-03T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  variables:
  - type: xlrelease.PasswordStringVariable
    key: Template.password
  scriptUsername: admin
  riskProfile: Default risk profile
- name: Test DashBoard
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 0
  - name: JIRA issues
    type: jira.JiraQueryTile
    row: 0
    col: 1
    jiraServer: Digital
    username: sivaprasath.subramaniyan@digital.ai
    password: !value "jira_JiraQueryTile_JIRA_issues_password"
    query: select * from table
  - name: Latest commits
    type: test.LatestCommitsTile
    row: 0
    col: 2
    supportedScopes:
    - release
    - folder
    - global
  - name: Top 10 task assignees
    type: xlrelease.TopTenTaskAssigneeTile
    row: 0
    col: 3
  columns: 8
- name: Test Triggers
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.PasswordValue
    targetProperty: "variables[Template.password]"
    value: !value "xlrelease_PasswordValue_value"
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Trigger-Template_r1
  - type: xlrelease.StringValue
    targetProperty: template
    value: Template One
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: Another Folder
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: Global Set
  eventType: events.HttpRequestEvent
- name: Another Trigger
  type: git.Poll
  releaseTitle: Test FA
  variables:
  - type: xlrelease.PasswordStringVariable
    key: Template.password
    value: !value "xlrelease_PasswordStringVariable_Template_password_value"
  template: Template One
  releaseFolder: ./
  gitRepository: firstGitRepository
  branch: main
  username: test
  password: !value "git_Poll_Another_Trigger_password"
