# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Jan 24 17:33:47 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8239
spec:
- directory: Sub-8239
  children:
  - directory: SubSub8239
    children:
    - pattern: SubSub8239
      stages:
      - stage: New Stage
      - stage: New Stage (1)
      - stage: New Stage (2)
    - template: Template Two
      scheduledStartDate: 2022-01-24T09:00:00+05:30
      phases:
      - phase: New Phase
        tasks:
        - name: MTG1
          type: xlrelease.Task
      riskProfile: Default risk profile
    - name: DashBoard
      type: xlrelease.BlankDashboard
      owner: admin
    - name: Trigger Test
      type: events.EventBasedTrigger
      enabled: false
      mappedProperties:
      - type: xlrelease.StringValue
        targetProperty: releaseTitle
        value: 8239_SUB_SUB
      - type: xlrelease.StringValue
        targetProperty: template
        value: Template Two
      - type: xlrelease.StringValue
        targetProperty: releaseFolder
        value: ENG-8239
      triggerActionType: xlrelease.CreateReleaseFromTemplateAction
      eventSource: ENG-8239
      eventType: events.HttpRequestEvent
    - name: Trigger Two
      type: jira.IssueTrigger
      enabled: false
      releaseTitle: Eng8239
      template: Template Two
      releaseFolder: ./
      jql: assignee ='test'
      server: Jira-test
  - name: Git-Rest
    type: git.Repository
    variableMapping:
      password: "${global.GLobalPass1}"
    url: https://github.com/SivaprasathDigitalAI/Test_versioning
    username: SivaprasathDigitalAI
  - pattern: Patter2
    stages:
    - stage: New Stage
  - pattern: Pattern
    stages:
    - stage: Stage One
    - stage: Stage two
  - pattern: p
    stages:
    - stage: New Stage
  - template: First Template
    scheduledStartDate: 2022-01-24T09:00:00+05:30
    phases:
    - phase: New Phase
      tasks:
      - name: MT
        type: xlrelease.Task
      - name: Custom
        type: databasePlugin.Oracle
        artifactory_url: https://artifactory.server.rbsgrp.net/artifactory
        artifactory_repo: test
        artifact_path: test
        artifact_name: test
        artifact_version: "123"
        property_env: local
        db_user: SivaprasathDigitalAI
        db_host: test
        db_port: "1452"
        database_name: Test
        variableMapping:
          pythonScript.db_password: "${global.GLobalPass1}"
      - name: g
        type: xlrelease.GateTask
    riskProfile: Default risk profile
  - name: dummy Dashboasrd
    type: xlrelease.BlankDashboard
    owner: admin
    tiles:
    - name: Active releases
      type: live.ReleasesTile
      row: 0
      col: 0
      filters:
      - type: xlrelease.TemplateFilter
        template: ./Template One
      - type: xlrelease.DateFilter
        timeFrame: LAST_MONTH
    - name: Active releases by risk
      type: live.ReleasesByRiskTile
      row: 0
      col: 2
      filters:
      - type: xlrelease.DateFilter
        timeFrame: LAST_MONTH
      - type: xlrelease.CompositeFilter
        filters:
        - type: xlrelease.FolderFilter
          folder: ./Sub-8239
    - name: Completed releases
      type: xlrelease.CompletedReleasesTile
      row: 0
      col: 4
    - name: Tile with custom config
      type: test.TestTileCustomConfig
      row: 0
      col: 5
      supportedScopes:
      - release
      - folder
      - global
  - name: Parent Trigger
    type: events.EventBasedTrigger
    enabled: false
    mappedProperties:
    - type: xlrelease.StringValue
      targetProperty: releaseTitle
      value: 8239_template
    - type: xlrelease.StringValue
      targetProperty: template
      value: First Template
    - type: xlrelease.StringValue
      targetProperty: releaseFolder
      value: ENG-8239/Sub-8239
    triggerActionType: xlrelease.CreateReleaseFromTemplateAction
    eventSource: Global Webhook
    eventType: events.HttpRequestEvent
  - name: Trigger One
    type: git.Poll
    enabled: false
    releaseTitle: SUb8239
    template: First Template
    releaseFolder: ./Sub-8239
    gitRepository: Github-8239
    branch: Main
- name: ENG-8239
  type: events.GetWebhookEndpoint
  path: eng8239
  authentication:
    type: events.NoAuthentication
- pattern: ENG-8239-Pattern
  stages:
  - stage: Stage One 8239
  - stage: Stage Two 8239
  trackedItems:
  - trackedItem: test
- template: Template One
  scheduledStartDate: 2022-01-21T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
    - name: External Delivery
      type: delivery.CreateDelivery
      ^title: ExternalDel1
      pattern: ./ENG-8239-Pattern
      folder: ./
      variableMapping:
        pythonScript.deliveryId: "${DeliveryId}"
    - name: Global Webhook
      type: webhook.WaitForJsonEvent
      endpoint: Global Webhook
      variableMapping:
        pythonScript.event: "${DeliveryId}"
    - name: Gate Tasks
      type: xlrelease.GateTask
      facets:
      - type: udm.DeploymentTaskFacet
        variableMapping:
          version: "${global.GLobalVar1}"
        application: External App1
        environment: Dev Env
      - type: udm.DeploymentTaskFacet
        version: V2
        application: Exxternal App2
        environment: Prod Env
  variables:
  - type: xlrelease.StringVariable
    key: DeliveryId
    requiresValue: false
    showOnReleaseStart: false
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_One_scriptUserPassword"
  riskProfile: Default risk profile
- name: ENG-8239-Dashboard
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 0
    col: 0
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    row: 0
    col: 1
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
  - name: JIRA issues
    type: jira.JiraQueryTile
    row: 0
    col: 2
    jiraServer: Jira-test
    apiToken: !value "jira_JiraQueryTile_JIRA_issues_apiToken"
    query: reporter ="Sivaprasath Subramaniyan"
- name: Git Trigger
  type: git.Poll
  enabled: false
  releaseTitle: ENG-8239
  template: Template One
  releaseFolder: ENG-8699
  gitRepository: Global
  branch: main
- name: cus
  type: test.CustomTypesTrigger
  enabled: false
  releaseTitle: custom
  template: Template One
  releaseFolder: ./Sub-8239
  stringList:
  - test
  stringSet:
  - testSet
  stringMap:
    key: value
- name: Time Based 8239
  type: time.Schedule
  releaseTitle: TimeBased8239
  template: Template One
  releaseFolder: ENG-8699
  periodicity: 0 0 9-17 * * MON-FRI
  enabled: false
  triggerTime: 2022-01-24T12:00:00.316000
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: ENG-8239
spec:
- directory: "."
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: ApplyVersionTeam
    users:
    - Test
    permissions:
    - template#view
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#create_release
    - template#edit_precondition
    - template#edit_failure_handler
  - name: TestTeam2
    users:
    - Test2
    permissions:
    - delivery_pattern#view
    - template#view
- directory: Sub-8239
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: ApplyVersionTeam
    users:
    - Test
    permissions:
    - template#view
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#create_release
    - template#edit_precondition
    - template#edit_failure_handler
  - name: TestTeam2
    users:
    - Test2
    permissions:
    - delivery_pattern#view
    - template#view
- directory: Sub-8239/SubSub8239
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: ApplyVersionTeam
    users:
    - Test
    permissions:
    - template#view
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#create_release
    - template#edit_precondition
    - template#edit_failure_handler
  - name: TestTeam2
    users:
    - Test2
    permissions:
    - delivery_pattern#view
    - template#view
