# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Mar 01 15:32:01 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: TT
spec:
- template: Check_Configuration
  scheduledStartDate: 2023-02-24T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: JS
      type: xlrelease.ScriptTask
      script: |-
        result = configurationApi.checkStatus("Configuration/Custom/Configuration005aba047b8246c98d21c187acfa5cc7")
        print result.scriptFound
        print result.errorText
        print result.success
    - name: MT
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Check_Configuration_scriptUserPassword"
  extensions:
  - name: Dashboard
    type: xlrelease.Dashboard
    owner: admin
    tiles:
    - name: Release progress
      type: xlrelease.ReleaseProgressTile
    - name: Release summary
      type: xlrelease.ReleaseSummaryTile
    - name: Resource usage
      type: xlrelease.ResourceUsageTile
    - name: Release timeline
      type: xlrelease.TimelineTile
    - name: Release health
      type: xlrelease.ReleaseHealthTile
  riskProfile: Default risk profile
